with-expecter: true
boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/dfg007star/go_rocket/payment/internal/service:
    config:
      include-regex: ".*Service"

  github.com/dfg007star/go_rocket/payment/internal/repository:
    config:
      include-regex: ".*Repository"
