// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/session.proto

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionUuid сессия пользователя
type SessionUuid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionUuid   string                 `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionUuid) Reset() {
	*x = SessionUuid{}
	mi := &file_common_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionUuid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionUuid) ProtoMessage() {}

func (x *SessionUuid) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionUuid.ProtoReflect.Descriptor instead.
func (*SessionUuid) Descriptor() ([]byte, []int) {
	return file_common_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *SessionUuid) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

var File_common_v1_session_proto protoreflect.FileDescriptor

const file_common_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x17common/v1/session.proto\x12\tcommon.v1\"0\n" +
	"\vSessionUuid\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuidBFZDgithub.com/dfg007star/go_rocket/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_session_proto_rawDescOnce sync.Once
	file_common_v1_session_proto_rawDescData []byte
)

func file_common_v1_session_proto_rawDescGZIP() []byte {
	file_common_v1_session_proto_rawDescOnce.Do(func() {
		file_common_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_session_proto_rawDesc), len(file_common_v1_session_proto_rawDesc)))
	})
	return file_common_v1_session_proto_rawDescData
}

var file_common_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_session_proto_goTypes = []any{
	(*SessionUuid)(nil), // 0: common.v1.SessionUuid
}
var file_common_v1_session_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_session_proto_init() }
func file_common_v1_session_proto_init() {
	if File_common_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_session_proto_rawDesc), len(file_common_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_session_proto_goTypes,
		DependencyIndexes: file_common_v1_session_proto_depIdxs,
		MessageInfos:      file_common_v1_session_proto_msgTypes,
	}.Build()
	File_common_v1_session_proto = out.File
	file_common_v1_session_proto_goTypes = nil
	file_common_v1_session_proto_depIdxs = nil
}
