// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/v1/user.proto

package common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotificationMethod канал связи
type NotificationMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"` // например, telegram, email, push)
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`                                 // email, ID telegram и т.д.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMethod) Reset() {
	*x = NotificationMethod{}
	mi := &file_common_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMethod) ProtoMessage() {}

func (x *NotificationMethod) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMethod.ProtoReflect.Descriptor instead.
func (*NotificationMethod) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationMethod) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *NotificationMethod) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

// UserInfo информация о пользователе
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_common_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UserInfo) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_common_v1_user_proto protoreflect.FileDescriptor

const file_common_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x14common/v1/user.proto\x12\tcommon.v1\"Q\n" +
	"\x12NotificationMethod\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"S\n" +
	"\bUserInfo\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05emailBFZDgithub.com/dfg007star/go_rocket/shared/pkg/proto/common/v1;common_v1b\x06proto3"

var (
	file_common_v1_user_proto_rawDescOnce sync.Once
	file_common_v1_user_proto_rawDescData []byte
)

func file_common_v1_user_proto_rawDescGZIP() []byte {
	file_common_v1_user_proto_rawDescOnce.Do(func() {
		file_common_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_user_proto_rawDesc), len(file_common_v1_user_proto_rawDesc)))
	})
	return file_common_v1_user_proto_rawDescData
}

var file_common_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_v1_user_proto_goTypes = []any{
	(*NotificationMethod)(nil), // 0: common.v1.NotificationMethod
	(*UserInfo)(nil),           // 1: common.v1.UserInfo
}
var file_common_v1_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_user_proto_init() }
func file_common_v1_user_proto_init() {
	if File_common_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_user_proto_rawDesc), len(file_common_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_user_proto_goTypes,
		DependencyIndexes: file_common_v1_user_proto_depIdxs,
		MessageInfos:      file_common_v1_user_proto_msgTypes,
	}.Build()
	File_common_v1_user_proto = out.File
	file_common_v1_user_proto_goTypes = nil
	file_common_v1_user_proto_depIdxs = nil
}
