{
 "title": "Go Rocket Service Overview",
 "description": "Основные метрики Go Rocket сервиса",
 "tags": [
  "go_rocket",
  "microservice"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Orders Total",
   "type": "timeseries",
   "description": "Количество заказов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(orders_total[1m])", "legendFormat": "{{method}} - {{status}}" }
   ]
  },
  {
   "title": "Orders Revenue Dashboard",
   "type": "timeseries",
   "description": "Мониторинг выручки от заказов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "orders_revenue_total", "legendFormat": "Total Revenue" },
    { "expr": "rate(orders_revenue_total[5m])", "legendFormat": "Revenue/sec (5m avg)" }
   ]
  },
  {
   "title": "Assembly Duration",
   "type": "timeseries",
   "description": "Время выполнения сборки заказов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(assembly_duration_seconds_bucket[5m]))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, rate(assembly_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, rate(assembly_duration_seconds_bucket[5m]))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, rate(assembly_duration_seconds_bucket[5m]))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}