// Code generated by ogen, DO NOT EDIT.

package order_v1

// setDefaults set default value of fields.
func (s *PayOrderRequest) setDefaults() {
	{
		val := PayOrderRequestPaymentMethod("UNKNOWN")
		s.PaymentMethod = val
	}
}
