// Code generated by ogen, DO NOT EDIT.
package order_v1

type CancelOrderByUuidRes interface {
	cancelOrderByUuidRes()
}

type CreateOrderRes interface {
	createOrderRes()
}

type OrderByUuidRes interface {
	orderByUuidRes()
}

type PayOrderRes interface {
	payOrderRes()
}
